config:
  jpa:
    action: none
  flyway:
    enabled: false
  notification:
    recipient: dummy@host.com
    sender: dummy@host.com
  integration:
    invoicecache:
      connectTimeout: 10
      readTimeout: 20
    messaging:
      connectTimeout: 10
      readTimeout: 20
  scheduler:
    cron:
      dbcleaner: '-'
      invoiceexporter: '-'
      notifier: '-'