#-------------------------------------------------------------------------------
# OpenAPI/Swagger-UI
#-------------------------------------------------------------------------------
openapi:
    name: ${spring.application.name}
    title: ${spring.application.name}
    version: '@project.version@'
springdoc:
    swagger-ui:
        operationsSorter: method

#-------------------------------------------------------------------------------
# Spring
#-------------------------------------------------------------------------------
spring:
    application:
        name: api-seab-loader
    datasource:
        url: ${config.datasource.url}
        username: ${config.datasource.username}
        password: ${config.datasource.password}
        driver-class-name: org.mariadb.jdbc.Driver
        hikari:
            pool-name: seab-loader-pool
        type: com.zaxxer.hikari.HikariDataSource
    flyway:
        enabled: ${config.flyway.enabled}
    jpa:
        properties:
            jakarta:
                persistence:
                    schema-generation:
                        database:
                            action: ${config.jpa.action}
    security:
        oauth2:
            client:
                registration:
                    invoicecache:
                        authorization-grant-type: client_credentials
                        client-id: ${config.integration.invoicecache.client-id}
                        client-secret: ${config.integration.invoicecache.client-secret}
                        provider: invoicecache
                    messaging:
                        authorization-grant-type: client_credentials
                        client-id: ${config.integration.messaging.client-id}
                        client-secret: ${config.integration.messaging.client-secret}
                        provider: messaging
#-------------------------------------------------------------------------------
# TODO: Remove settings for dwr and party after completion of Stralfors invoices import
#-------------------------------------------------------------------------------
                    datawarehousereader:
                        authorization-grant-type: client_credentials
                        client-id: ${config.integration.datawarehousereader.client-id}
                        client-secret: ${config.integration.datawarehousereader.client-secret}
                        provider: datawarehousereader
                    party:
                        authorization-grant-type: client_credentials
                        client-id: ${config.integration.party.client-id}
                        client-secret: ${config.integration.party.client-secret}
                        provider: party
                provider:
                    invoicecache:
                        token-uri: ${config.integration.token-uri}
                    messaging:
                        token-uri: ${config.integration.token-uri}
#-------------------------------------------------------------------------------
# TODO: Remove settings for dwr and party after completion of Stralfors invoices import
#-------------------------------------------------------------------------------
                    datawarehousereader:
                        token-uri: ${config.integration.token-uri}
                    party:
                        token-uri: ${config.integration.token-uri}

#-------------------------------------------------------------------------------
# Integration settings
#-------------------------------------------------------------------------------
integration:
    invoicecache:
        url: ${config.integration.invoicecache.url}
        connectTimeout: ${config.integration.invoicecache.connectTimeout}
        readTimeout: ${config.integration.invoicecache.readTimeout}
    messaging:
        url: ${config.integration.messaging.url}
        connectTimeout: ${config.integration.messaging.connectTimeout}
        readTimeout: ${config.integration.messaging.readTimeout}
#-------------------------------------------------------------------------------
# TODO: Remove settings for dwr and party after completion of Stralfors invoices import
#-------------------------------------------------------------------------------
    datawarehousereader:
        url: ${config.integration.datawarehousereader.url}
        connectTimeout: ${config.integration.datawarehousereader.connectTimeout}
        readTimeout: ${config.integration.datawarehousereader.readTimeout}
    party:
        url: ${config.integration.party.url}
        connectTimeout: ${config.integration.party.connectTimeout}
        readTimeout: ${config.integration.party.readTimeout}

resilience4j:
    circuitbreaker:
        instances:
            invoicecache:
                ignoreExceptions: se.sundsvall.dept44.exception.ClientProblem
            messaging:
                ignoreExceptions: se.sundsvall.dept44.exception.ClientProblem
#-------------------------------------------------------------------------------
# TODO: Remove settings for dwr and party after completion of Stralfors invoices import
#-------------------------------------------------------------------------------
            datawarehousereader:
                ignoreExceptions: se.sundsvall.dept44.exception.ClientProblem
            party:
                ignoreExceptions: se.sundsvall.dept44.exception.ClientProblem

#-------------------------------------------------------------------------------
# Log config
#-------------------------------------------------------------------------------
logbook:
    exclusionfilters:
        json-path: '{''$..content'' : ''[base64]''}'
        x-path: '{''//*[contains(@name, ".pdf")]'' : ''[base64]''}'
logging:
    level:
        org:
            apache:
                pdfbox:
                    pdmodel: INFO
        root: INFO

#-------------------------------------------------------------------------------
# Notification (e.g. mail notifications for system events)
#-------------------------------------------------------------------------------
notification:
    mail:
        enabled: true
        recipient:
            address: ${config.notification.recipient}
        sender:
            address: ${config.notification.sender}

#-------------------------------------------------------------------------------
# Scheduler settings
# - To disable a specific schedule, set cron expression to "-"
#   or remove property for the specific schedule.
#-------------------------------------------------------------------------------
scheduler:
    dbcleaner:
        cron:
            expression: ${config.scheduler.cron.dbcleaner}
    invoiceexporter:
        cron:
            expression: ${config.scheduler.cron.invoiceexporter}
    notifier:
        cron:
            expression: ${config.scheduler.cron.notifier}

#-------------------------------------------------------------------------------
# TODO: Remove settings below after completion of Stralfors invoices import
#-------------------------------------------------------------------------------
api:
    batchimportresource:
        rootpath: ${config.api.batchimportresource.rootpath:}
            